name: mlops
on: [push]
jobs:
  run_on_powermachine:
    # runs-on: [ubuntu-latest]
    # container: docker://dvcorg/cml-py3:latest
    runs-on: [powermachine]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $(which python)
          echo $(which conda)
          CODEBLOCK="\`\`\`"
          echo $CODEBLOCK > report.md
          nvidia-smi >> report.md
          echo $CODEBLOCK >> report.md

          source $CONDA_PREFIX/etc/profile.d/conda.sh
          conda activate mlops
          python -m pip install -r requirements.txt
          dvc repro

          git fetch --prune # gets git history of the runner
          dvc metrics diff --show-md main >> report.md

          # echo "## Model metrics" > report.md
          # cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md

          cml-send-comment report.md
